# Generated by Django 4.0.10 on 2024-07-29 21:54

import cm_db.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('nodeid', models.CharField(default='', max_length=20, primary_key=True, serialize=False)),
                ('outcome', models.CharField(default='', max_length=20)),
                ('result', djongo.models.fields.ArrayField(model_container=cm_db.models.Result, model_form_class=cm_db.models.Result_Form)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
