import pymongo
import json
import os
from settings import BASE_DIR
from pymongo import MongoClient, InsertOne

IMPORT_DIR = os.path.join(BASE_DIR, "imports")
print("IMPORT DIRECTORY:", IMPORT_DIR)

#this needs to somehow read .json files generated by our test program and add them as entries to the database.
#hopefully simple as pulling individual variables out of the file and submitting them through the django ORM functions...

def upload_json(filename):
    client = pymongo.MongoClient('mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.2.12')
    db = client.db
    collection = db.cm_db_cm_test_result
    requesting = []
    filepath = os.path.join(IMPORT_DIR, filename)
    with open(filepath, 'r+') as f:
        print(f)
        newobj = ''
        for line in f.readlines():
            newln = line.strip()
            newobj += newln
        print(f"{newobj = }")
        s = newobj
        #s = s.replace('\t','')
        #s = s.replace('\n','')
        #s = s.replace(',}','}')
        #s = s.replace(',]',']')  
        s = s.replace('environment: {}', 'environment: {}')
        myDict = json.loads(s)
        requesting.append(InsertOne(myDict))
    result = collection.bulk_write(requesting)
    client.close()
    return 1

if __name__ == "__main__":
    upload_json("report_mezz_2024-07-24_20-32-33.json")
